#!/usr/bin/env bash

# xamarth

echo "

      Made with ❤️ by @xamarth | @riotoreo

"

if [ -f .env ] ; then  set -o allexport; source .env; set +o allexport ; fi
if [ $SESSION1 ] ; then python3 multi_client.py ; else python3 -m pyCore ; fi
